---
  - hosts: localhost
    gather_facts: no
    tasks:
    - name: Add project
      ansible.controller.project:
        controller_host: "{{ controller_host }}"
        controller_oauthtoken: "{{ controller_oauthtoken }}"
        controller_password: "{{ controller_password }}"
        name: "{{ project_name }}"
        description: "{{ project_name }} project requested by SNOW {{ snow_request }}"
        organization: "Default"
        scm_type: git
        scm_update_on_launch: True
        scm_update_cache_timeout: 60
        scm_url: "{{ git_url }}"
        state: present

    - name: Create new user
      ansible.controller.tower_user:
        controller_host: "{{ controller_host }}"
        controller_oauthtoken: "{{ controller_oauthtoken }}"
        controller_password: "{{ controller_password }}"
        username: skozlov
        password: "{{ lookup('ansible.builtin.password') }}"
        email: skozlov@redhat.com
        first_name: Stan
        last_name: Kozlov
        state: present

    - name: Create new team
      ansible.controller.team:
        controller_host: "{{ controller_host }}"
        controller_oauthtoken: "{{ controller_oauthtoken }}"
        controller_password: "{{ controller_password }}"
        name: redhat-automation
        description: "Red Hat Automation Team. Requested by SNOW {{ snow_request }}"
        organization: Default
        state: present    

    - name: Add user to the team
      ansible.controller.role:
        controller_host: "{{ controller_host }}"
        controller_oauthtoken: "{{ controller_oauthtoken }}"
        controller_password: "{{ controller_password }}"
        user: skozlov
        target_team: "redhat-automation"
        role: admin
        state: present

    - name: Bind team to project
      ansible.controller.role:
        controller_host: "{{ controller_host }}"
        controller_oauthtoken: "{{ controller_oauthtoken }}"
        controller_password: "{{ controller_password }}"
        project: "{{ project_name }}"
        team: "redhat-automation"
        role: admin
        state: present

    - name: Bind inventory to project
      ansible.controller.role:
        controller_host: "{{ controller_host }}"
        controller_oauthtoken: "{{ controller_oauthtoken }}"
        controller_password: "{{ controller_password }}"
        inventory: "production"
        team: "redhat-automation"
        role: admin
        state: present